version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./settings.js:/var/cloud9/settings.js:cached
    ports:
      - "${APP_PORT:-3000}:3000"
